### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x7f020052

### ISSUE THREAD

**Issue by lectricas** [goofyahead/dagger2structureSample#3]
when trying to run TestMainActivity.
Not sure why this is happening

**Comment by TonyTangAndroid** [comment]
I ran into the same problem today.

android.content.res.Resources$NotFoundException: Resource ID #0x7f020052

	at android.content.res.Resources.getValue(Resources.java:1233)
	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
